PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE book (
    id INTEGER PRIMARY KEY,
    name_en TEXT NOT NULL,
    name_cn TEXT NOT NULL,
    testament TEXT NOT NULL,
    order_index INTEGER NOT NULL
);
INSERT INTO book VALUES(1,'Genesis','创世纪','Old',1);
INSERT INTO book VALUES(2,'Exodus','出谷纪','Old',2);
INSERT INTO book VALUES(3,'Leviticus','肋未纪','Old',3);
INSERT INTO book VALUES(4,'Numbers','户籍纪','Old',4);
INSERT INTO book VALUES(5,'Deuteronomy','申命纪','Old',5);
INSERT INTO book VALUES(6,'Joshua','若苏厄书','Old',6);
INSERT INTO book VALUES(7,'Judges','民长纪','Old',7);
INSERT INTO book VALUES(8,'Ruth','卢德传','Old',8);
INSERT INTO book VALUES(9,'1 Samuel','撒慕尔纪上','Old',9);
INSERT INTO book VALUES(10,'2 Samuel','撒慕尔纪下','Old',10);
INSERT INTO book VALUES(11,'1 Kings','列王纪上','Old',11);
INSERT INTO book VALUES(12,'2 Kings','列王纪下','Old',12);
INSERT INTO book VALUES(13,'1 Chronicles','编年纪上','Old',13);
INSERT INTO book VALUES(14,'2 Chronicles','编年纪下','Old',14);
INSERT INTO book VALUES(15,'Ezra','厄斯德拉上','Old',15);
INSERT INTO book VALUES(16,'Nehemiah','厄斯德拉下(乃赫米雅)','Old',16);
INSERT INTO book VALUES(17,'Tobit','多俾亚传','Old',17);
INSERT INTO book VALUES(18,'Judith','友弟德传','Old',18);
INSERT INTO book VALUES(19,'Esther','艾斯德尔传','Old',19);
INSERT INTO book VALUES(20,'1 Maccabees','玛加伯上','Old',20);
INSERT INTO book VALUES(21,'2 Maccabees','玛加伯下','Old',21);
INSERT INTO book VALUES(22,'Job','约伯传','Old',22);
INSERT INTO book VALUES(23,'Psalms','圣咏集','Old',23);
INSERT INTO book VALUES(24,'Proverbs','箴言篇','Old',24);
INSERT INTO book VALUES(25,'Ecclesiastes','训道篇','Old',25);
INSERT INTO book VALUES(26,'Song of Solomon','雅歌','Old',26);
INSERT INTO book VALUES(27,'Wisdom','智慧篇','Old',27);
INSERT INTO book VALUES(28,'Sirach','德训篇','Old',28);
INSERT INTO book VALUES(29,'Isaiah','依撒意亚','Old',29);
INSERT INTO book VALUES(30,'Jeremiah','耶肋米亚','Old',30);
INSERT INTO book VALUES(31,'Lamentations','哀歌','Old',31);
INSERT INTO book VALUES(32,'Baruch','巴路克','Old',32);
INSERT INTO book VALUES(33,'Ezekiel','厄则克耳','Old',33);
INSERT INTO book VALUES(34,'Daniel','达尼尔','Old',34);
INSERT INTO book VALUES(35,'Hosea','欧瑟亚','Old',35);
INSERT INTO book VALUES(36,'Joel','岳厄尔','Old',36);
INSERT INTO book VALUES(37,'Amos','亚毛斯','Old',37);
INSERT INTO book VALUES(38,'Obadiah','亚北底亚','Old',38);
INSERT INTO book VALUES(39,'Jonah','约纳','Old',39);
INSERT INTO book VALUES(40,'Micah','米该亚','Old',40);
INSERT INTO book VALUES(41,'Nahum','纳鸿','Old',41);
INSERT INTO book VALUES(42,'Habakkuk','哈巴谷','Old',42);
INSERT INTO book VALUES(43,'Zephaniah','索福尼亚','Old',43);
INSERT INTO book VALUES(44,'Haggai','哈盖','Old',44);
INSERT INTO book VALUES(45,'Zechariah','匝加利亚','Old',45);
INSERT INTO book VALUES(46,'Malachi','玛拉基雅','Old',46);
INSERT INTO book VALUES(47,'Matthew','玛窦福音','New',47);
INSERT INTO book VALUES(48,'Mark','马尔谷福音','New',48);
INSERT INTO book VALUES(49,'Luke','路加福音','New',49);
INSERT INTO book VALUES(50,'John','若望福音','New',50);
INSERT INTO book VALUES(51,'Acts','宗徒大事录','New',51);
INSERT INTO book VALUES(52,'Romans','罗马书','New',52);
INSERT INTO book VALUES(53,'1 Corinthians','格林多前书','New',53);
INSERT INTO book VALUES(54,'2 Corinthians','格林多后书','New',54);
INSERT INTO book VALUES(55,'Galatians','迦拉达人书','New',55);
INSERT INTO book VALUES(56,'Ephesians','厄弗所书','New',56);
INSERT INTO book VALUES(57,'Philippians','斐理伯人书','New',57);
INSERT INTO book VALUES(58,'Colossians','哥罗森人书','New',58);
INSERT INTO book VALUES(59,'1 Thessalonians','得撒洛尼前书','New',59);
INSERT INTO book VALUES(60,'2 Thessalonians','得撒洛尼后书','New',60);
INSERT INTO book VALUES(61,'1 Timothy','弟茂德前书','New',61);
INSERT INTO book VALUES(62,'2 Timothy','弟茂德后书','New',62);
INSERT INTO book VALUES(63,'Titus','弟铎书','New',63);
INSERT INTO book VALUES(64,'Philemon','费肋孟书','New',64);
INSERT INTO book VALUES(65,'Hebrews','希伯来人书','New',65);
INSERT INTO book VALUES(66,'James','雅各伯书','New',66);
INSERT INTO book VALUES(67,'1 Peter','伯多禄前书','New',67);
INSERT INTO book VALUES(68,'2 Peter','伯多禄后书','New',68);
INSERT INTO book VALUES(69,'1 John','若望一书','New',69);
INSERT INTO book VALUES(70,'2 John','若望二书','New',70);
INSERT INTO book VALUES(71,'3 John','若望三书','New',71);
INSERT INTO book VALUES(72,'Jude','犹达书','New',72);
INSERT INTO book VALUES(73,'Revelation','若望默示录','New',73);
COMMIT;
